### ISSUE TITLE
[Enhancement] Create project specific admins

### ISSUE THREAD

**Issue by anshooarora** [anshooarora/klov#1]
Provide the ability to have unique admins for each project. 

This issue was taken from the deprecated ExtentX server.  [link](https://github.com/anshooarora/extentx/issues/165).

**Comment by ashokkumarg** [comment]
Which means
User 1 & User 2 can view the Project 1
User 3 & User 4 can view the Project 2
So the users can be linked to the specific projects??

**Comment by anshooarora** [comment]
This is specifically for admins. But the same applies to users.

**Comment by anshooarora** [comment]
Project specific admins is planned and in-progress for 0.1.5.

Sources along with this feature will be released soon.
