### ISSUE TITLE
Usage of extent schema in mongoDB to save report through Klov

### ISSUE THREAD

**Issue by arunkumarkmj** [anshooarora/klov#10]
I was using ExtentX server and all my earlier data is in my mongoDB within schema 'extent'.

Now i tried switching to Klov and klov reporting dashboard can read earlier data by configuring its application.properties to point to 'extent' schema.

But when I create new report , all entries are going under a new schema 'klov' in DB . How can I control this and redirect my data to older schema instead.

Let me know if I am missing out anything here to map.

**Comment by anshooarora** [comment]
ExtentX schema will not work with klov. I would suggest using both klov and ExtentX reporters for a few days and stop using ExtentX when you have ample data for klov.
