### ISSUE TITLE
Failed Test are not displayed

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/klov#11]
@anshooarora Thanks for this awesome project.

I started using klov as part of AppiumTestDistribution, i did notice few things

[ ] Failed tests are not displayed, but extentreports is showing expected values 

![screen shot 2017-11-24 at 9 16 38 am](https://user-images.githubusercontent.com/4045041/33203365-a49777e0-d0f7-11e7-9589-3f5f36e1090d.png)

![screen shot 2017-11-24 at 9 16 46 am](https://user-images.githubusercontent.com/4045041/33203369-a6e6cd20-d0f7-11e7-97e9-3030719c94c7.png)

[ ] Categories are not linked to the tests that its tagged.

**Comment by anshooarora** [comment]
Hi Sai

Can you help me repro the issue with statuses not updating?  

For categories,  its something that I haven't added to the view yet, but will and release it early next week.

**Comment by saikrishna321** [comment]
@anshooarora here is example pls give it a try 

https://github.com/saikrishna321/extent_reports/tree/klov

**Comment by anshooarora** [comment]
Sai,  I tested your sample project using:

```
mvn clean -Dtest=Runner test
```

I am seeing all failed tests here.  Is there a different way you are running?

![img](https://user-images.githubusercontent.com/4107384/33318023-2542ecdc-d407-11e7-8f6e-7ed280f00b7a.png)

**Comment by saikrishna321** [comment]
@anshooarora  🤓 works for me as well... i had to clear the klov , extent DB and it works.. I didnt work  here (https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumParallelMethodTestListener.java#L18) let me check again 

Is it needed always that we need to initialize klov and extentX ? coz when i have klov alone i dont see the reports. It should always be this 

extent.attachReporter(getHtmlReporter(),klovReporter(),getExtentXReporter());

```
private static ExtentXReporter getExtentXReporter() {
        //String host = prop.getProperty("MONGODB_SERVER");
        //Integer port = Integer.parseInt(prop.getProperty("MONGODB_PORT"));
        ExtentXReporter extentx = new ExtentXReporter("localhost", 27017);

        // project name
        String projectName = prop.getProperty("projectName", "ExtentReports");
        extentx.config().setProjectName(projectName);

        // report or build name
        String reportName = prop.getProperty("reportName", "ExtentReports");
        extentx.config().setReportName(reportName);

        // server URL
        // ! must provide this to be able to upload snapshots

        return extentx;
    }

```  


Keeping it open till i get it fixed in the AppiumParallelDistribution FW

**Comment by saikrishna321** [comment]
@anshooarora  i see this exception

```
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 192.168.1.8:27017/csrfToken
```

this occurs when i add screenshot 

log.addScreenCaptureFromPath("something")

**Comment by anshooarora** [comment]
The above issue comes from ExtentX - from the csrfToken route.  It is thrown when the IP is generally not correct, which I believe in your case should be: `192.168.1.8:1337/csrfToken` instead of `192.168.1.8:27017/csrfToken`.  Notice the ports,  the URI you have used is pointing to the port of the MongoDB server.

**Comment by anshooarora** [comment]
Also, you don't need ExtentX at all.

**Comment by anshooarora** [comment]
Actually, do not use ExtentX with klov. There will be issues - use either, in this case klov only.

ExtentX is no longer supported

**Comment by saikrishna321** [comment]
@anshooarora can't klov alone working, can you try with the same repo provided. I removed ExtentX usage and the reports are not getting created under klov server 

I see some errors when running klov.jar 

https://gist.github.com/saikrishna321/cc9f8e7c3a3bca26f030d55b89811699

Waiting to hear from you

**Comment by anshooarora** [comment]
Sai

I was able to reproduce these issues.

I have made several fixes this morning and also added the features you had raised.  Please download the latest (0.0.2) from http://extentreports.com/community/.  

From `application.properties`, klov will run on port 80 and mongodb use will the `klov` database:

```
# klov
application.name=klov
server.port=80

# data.mongodb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=klov
```

**Comment by saikrishna321** [comment]
@anshooarora Thanks a lot for quick fix... Works now 👍 

Skipped test is marked as Pass. Pls refer screen

<img width="914" alt="screen shot 2017-11-29 at 10 40 04 pm" src="https://user-images.githubusercontent.com/4045041/33388574-4fb9334a-d556-11e7-9ea8-9f4fc6f3884d.png">

**Comment by anshooarora** [comment]
It could be because you have set a custom hierarchy here:

https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/report/factory/ExtentManager.java

Causing Pass to have a higher priority.

**Comment by anshooarora** [comment]
Ideally Skip should have a higher priority. Any skipped step would cause the entire test to skip even if there are other passed events.

**Comment by saikrishna321** [comment]
@anshooarora 
> Any skipped step would cause the entire test to skip even if there are other passed events

This holds good when your on BDD scenario

Consider TestNG as FW, when you have marked a single test skipped intentionally( for ex: In a project  which is cross platform app(android/ios/mweb) with different product owners  and the feature gets developed only for android and not for iOS in such case we tent to skip the test on iOS platform. Now if the LoginTest class has one test skipped the DashBoard would should LoginTest skipped, which people think the entire test got skipped.

> Check the ExtentReport.html file created, it would also have "Pass" indicated.

NO, that shows skipped. Please check the screen below 

<img width="1400" alt="screen shot 2017-11-30 at 5 54 15 am" src="https://user-images.githubusercontent.com/4045041/33406432-ec9b4c20-d592-11e7-8868-cbb94839a5eb.png">

**Comment by anshooarora** [comment]
Hmm, are you doing something to set the status to Skip to the Html report?  I don't see how it is possible for the status to show Skip here but Pass in klov unless the underlying model gets changed without an update to the klov database.

**Comment by anshooarora** [comment]
What you are saying also makes sense, but I need to think of a way to do this without breaking the existing usage for others.

**Comment by anshooarora** [comment]
Please try with [3.1.2-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/aventstack/extentreports/3.1.2-SNAPSHOT/):

```
<!-- pom.xml -->
<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>3.1.2-SNAPSHOT</version>
</dependency>
```

Please remove this override:  https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/report/factory/ExtentManager.java#L48 and try again.  The override will break the default behavior.

**Comment by saikrishna321** [comment]
@anshooarora Works well :) Awesome .. thanks 🍾  Reporting looks really good .. will test it  .. closing as fixed 

```
<!-- pom.xml -->
<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>3.1.2-SNAPSHOT</version>
</dependency>
```
