### ISSUE TITLE
org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexResolver$CyclicPropertyReferenceException: Found cycle for field 'nodes' in type 'Test' for path ''

### ISSUE THREAD

**Issue by t-node** [anshooarora/klov#13]
When I am starting the klov server, I don't know why i am getting this error:
org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexResolver$CyclicPropertyReferenceException: Found cycle for field 'nodes' in type 'Test' for path ''

**Comment by karthikbhatnagar** [comment]
This error can be ignored.. just an info message.
