### ISSUE TITLE
Different BDD style Klov report

### ISSUE THREAD

**Issue by andisan86** [anshooarora/klov#15]
Hi @anshooarora , I was just trying out the Klov report, and noticed that my BDD style report looked remarkably different from your example:
![image](https://user-images.githubusercontent.com/24508969/34661026-b80b1540-f481-11e7-978e-1ec34e28f320.png)

In general, I followed these [steps](http://extentreports.com/docs/versions/3/java/#create-bdd-tests) to create a report:
1. Create new ExtentReports() object and attach HTML and Klov reporters into it.
2. Create a test ("feature") by createTest() method
3. Create additional node as required (Then/When/pass/fail etc)

Any pointer that you could share regarding this?

**Comment by andisan86** [comment]
I noticed that my report seems to be classified as "non BDD".
![image](https://user-images.githubusercontent.com/24508969/34702874-1fda1b54-f52b-11e7-9420-4ca237f6d697.png)
![image](https://user-images.githubusercontent.com/24508969/34702887-3030e79e-f52b-11e7-8b00-438b9dc20dcd.png)

My code snippet:
```
ExtentReports extent = new ExtentReports();
KlovReporter klov = new KlovReporter();
klov.initMongoDbConnection("localhost", 27017);
klov.setProjectName("Test Project");
klov.setReportName("Andi Test 3");
klov.setKlovUrl("http://localhost:1337");
extent.attachReporter(klov);
ExtentTest feature = extent.createTest("A Feature Name");
ExtentTest scenario = feature.createNode(Scenario.class, "A Scenario Name");
scenario.createNode(Given.class, "A Given Step");
```

I think Klov is supposed to automatically determine the report style? Any pointer on why it is using a non-BDD style?

**Comment by anshooarora** [comment]
That is because the parent-most test (Feature) is not started as a BDD (IGherkinFormatterModel) test. You need to start your test as:

```
ExtentTest feature = extent.createTest(Feature.class, "Refund item");
```

or

```
ExtentTest feature = extent.createTest(new GherkinKeyword("Feature"), "Refund item");
```

See here:  http://extentreports.com/docs/versions/3/java/#create-bdd-tests
