### ISSUE TITLE
getting NullPointerException  when trying to use klov

### ISSUE THREAD

**Issue by NaveenAutomate** [anshooarora/klov#16]
java.lang.NullPointerException
	at com.aventstack.extentreports.reporter.KlovReporter.onTestStarted(KlovReporter.java:428)
	at com.aventstack.extentreports.Report.lambda$createTest$0(Report.java:71)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.aventstack.extentreports.Report.createTest(Report.java:71)
	at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:232)
	at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:245)

code:
in before suite:

KlovReporter klov = new KlovReporter();

		// specify mongoDb connection
		klov.initMongoDbConnection("localhost", 27017);

		// specify project
		// ! you must specify a project, other a "Default project will be used"
		klov.setProjectName("Java");

		// you must specify a reportName otherwise a default timestamp will be used
		klov.setReportName("AppBuild");

		// URL of the KLOV server
		// you must specify the server URL to ensure all your runtime media is uploaded
		// to the server
		klov.setKlovUrl("http://localhost:1337/");

in before class:
i am creating new test using below statement and here i am facing nullPointer Exception. Stack trace given above.

extnTest = extentReporterNew.createTest(getClass().getName());

**Comment by anshooarora** [comment]
Version of API?  Do you have Mongo Db installed on your localhost?  Is the Klov server running when you get this error?  Is the URL correct?  You haven't provided any details other than the exception which is thrown by the API not the server

**Comment by NaveenAutomate** [comment]
Hi Anshoo,

Sorry for missing clarity.
API version- 3.1.2
klov- 0.0.3
I don't have redis, using without redis.

I am not seeing any log in either klov or mongod ( i mean no exception in server).

When i tried to debug i found here(in below mentioned statement) it is throwing exception but it is not logged any where. mongoDB is up and running, i have verified even url is correct.

KlovReporter.start()-->  MongoDatabase db = mongoClient.getDatabase(DB_NAME);


MongoDriver API- i have below mongodriver dependencies in my pom
<dependency>
			<groupId>org.mongodb</groupId>
			<artifactId>mongo-java-driver</artifactId>
			<version>2.11.3</version>
		</dependency>
<dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver</artifactId>
            <version>3.3.0</version>
        </dependency>


Thanks in advance.

**Comment by NaveenAutomate** [comment]
Hi Anshoo,

Please look into this if you get some time. 

Thanks,
Naveen.

**Comment by anshooarora** [comment]
What is the Mongo Db version? You don't need to add any Mongo dependencies in your pom.xml.  Remove all of them and only add extentreports dependency.

**Comment by NaveenAutomate** [comment]
Thanks Anshoo. After removing Mongodb from pom it started working.
