### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by simpleTesting** [anshooarora/klov#17]
Hi,

I  am using Klov reporting server and I can see all the build status in builds tab, but when i click on the dashboard, Whitelabel error page is displayed.  Was there any thing i need to configure?

Thanks
Naveen

![kloverror](https://user-images.githubusercontent.com/21266123/34885001-850e9c58-f78c-11e7-9485-70d4ffcf2623.png)

**Comment by anshooarora** [comment]
Looks like you are using version mongodb 3.6. Downgrade to 3.2 and it should work.
