### ISSUE TITLE
Enable Klov Tags Dashboard

### ISSUE THREAD

**Issue by andisan86** [anshooarora/klov#18]
Hi @anshooarora ,

How do I enable the Tags dashboard view in Klov? I believe I have been logging my BDD scenario correctly to Klov, and the Tags link still does not appear.

![image](https://user-images.githubusercontent.com/24508969/35312484-9f170e28-00f6-11e8-81ac-55de2623b4f2.png)

Kind regards,
Andi

**Comment by anshooarora** [comment]
Hi Andi

This view is currently enabled by the pro version of the app only.
