### ISSUE TITLE
Dashboard throws error

### ISSUE THREAD

**Issue by jsa34** [anshooarora/klov#24]
When using community version 0.0.3 with latest MongoDB, the following error page is shown when clicking on Dashboard page:

There was an unexpected error (type=Internal Server Error, status=500).
Command execution failed: Error [The 'cursor' option is required, except for aggregate with the explain argument], Command = { "aggregate" : "test" , "pipeline" : [ { "$match" : { "name" : { "$ne" : null } , "status" : "fail"}} , { "$group" : { "_id" : "$name" , "total" : { "$sum" : 1}}} , { "$project" : { "total" : 1 , "_id" : 0 , "name" : "$_id"}}]}; nested exception is com.mongodb.MongoCommandException: Command failed with error 9: 'The 'cursor' option is required, except for aggregate with the explain argument' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "The 'cursor' option is required, except for aggregate with the explain argument", "code" : 9, "codeName" : "FailedToParse" }

Possibly related to the following?
https://stackoverflow.com/questions/48490380/spring-mongodb-aggregation-the-cursor-option-is-required

**Comment by anshooarora** [comment]
You need MongoDB version 3.2.  looks like you have 3.6.
