### ISSUE TITLE
Multiple builds being created for the same test run

### ISSUE THREAD

**Issue by jsa34** [anshooarora/klov#25]
Klov 0.0.3 (Community)
MongoDB (latest)

Using TestNG
![multiplebuilds](https://user-images.githubusercontent.com/31512041/36736212-f54c5c78-1bcf-11e8-9851-176f61839005.PNG)

**Comment by anshooarora** [comment]
Please share how you are initiating Klov and ExtentReports.

**Comment by jsa34** [comment]
I am now using MongoDB 3.2 as suggested in previous issue raised.

Still got the same issue, but build numbers are different.  Feature list displays in all builds, but only one has the steps for the tests (which are duplicated with the number of builds on the dashboard, i.e. if 3 builds are created for the same run, the first build has each step duplicated 3 times in each feature, but the builds are empty.

I am using https://github.com/email2vimalraj/CucumberExtentReporter but created my own fork, and all I have changed is I have replaced:

`    private static void setExtentReport() {
        if (extentReports != null) {
            return;
        }
        extentReports = new ExtentReports();
        ExtentProperties extentProperties = ExtentProperties.INSTANCE;
        if (extentProperties.getExtentXServerUrl() != null) {
            String extentXServerUrl = extentProperties.getExtentXServerUrl();
            try {
                URL url = new URL(extentXServerUrl);
                ExtentXReporter xReporter = new ExtentXReporter(url.getHost());
                xReporter.config().setServerUrl(extentXServerUrl);
                xReporter.config().setProjectName(extentProperties.getProjectName());
                extentReports.attachReporter(htmlReporter, xReporter);
                return;
            } catch (MalformedURLException e) {
                throw new IllegalArgumentException("Invalid ExtentX Server URL", e);
            }
        }
        extentReports.attachReporter(htmlReporter);
    }
`

To use klov reporter as so (and renamed the enum variables):
`    private static void setExtentReport() {
        if (extentReports != null) {
            return;
        }
        extentReports = new ExtentReports();
        ExtentProperties extentProperties = ExtentProperties.INSTANCE;
        if (extentProperties.getKlovServerUrl() != null) {
            String klovServerUrl = extentProperties.getKlovServerUrl();
            String mongoDbUrl = extentProperties.getMongoDbServerUrl();
            KlovReporter klovReporter = new KlovReporter();
            klovReporter.setKlovUrl(klovServerUrl);
            klovReporter.initMongoDbConnection(mongoDbUrl);
            klovReporter.setProjectName(extentProperties.getProjectName());
            extentReports.attachReporter(htmlReporter, klovReporter);
            return;
        }
        extentReports.attachReporter(htmlReporter);
    }
`

And I use the following in each runner:
`@CucumberOptions(
        glue = {"*****.stepdefs"},
        features = "target/test-classes/",
        tags = {"@*****"},
        plugin = {"*****.ExtentCucumberFormatter:"})
public class *****Test extends AbstractTestNGCucumberTests {
    @BeforeClass
    public static void setup() {
        ExtentProperties extentProperties = ExtentProperties.INSTANCE;
        extentProperties.setKlovServerUrl(KLOV_SERVER_URL);
        extentProperties.setProjectName(PROJECT_NAME);
   extentProperties.setMongoDbServerUrl(MONGODB_SERVER_HOST);    
}
}
`

**Comment by anshooarora** [comment]
Using in each runner looks like to be the cause.  Just need to do this once.

**Comment by anshooarora** [comment]
Also, ExtentX is no longer supported to I would recommend removing that and trying again.
