### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by akhiljosephk** [anshooarora/klov#26]
Client have recently upgraded from ExtentX to Klov. I have made changes for Klov in my Test Runner class. When I execute test cases, execution is success and project is displayed in the Klov dropdown. When I select my project, Whitelabel Error Page is displayed.  Can you suggest me some work around other than downgrading Mongo DB version? Below is my code snippet.

`@RunWith(Cucumber.class)
@CucumberOptions(plugin = {"com.cucumber.listener.ExtentCucumberFormatter:output/extent.html"},
        format = {"pretty",
        "html:target/cucumber-htmlreport",
        "junit:target/cucumber-junit-report/cuc.xml"}
        , glue = {"com.xxx.xxx"}
        , features = {"src/test/resources"}
        , tags = {"xxxx"}
)
public class TestRunner {

    private static KlovReporter klovReporter;

        @AfterClass
     public static void teardown() {
          String curDir=System.getProperty("user.dir");
          Reporter.loadXMLConfig(new File(curDir+"/src/test/resources/extent-config.xml"));
          Reporter.setSystemInfo("user", System.getProperty("user.name"));
          Reporter.setSystemInfo("os", "Windows");
          Reporter.setTestRunnerOutput("Test Execution result for test");
          Reporter.assignAuthor(AUTHOR);
          Reporter.getExtentReport().attachReporter(klovReporter);
   }

    @BeforeClass
    public static void setupListner() throws IOException {
            klovReporter = new KlovReporter();
            klovReporter.setProjectName(XXX);  // project name
            klovReporter.setReportName(XXX);  // build name
            klovReporter.setKlovUrl(EXTENT_URL);  // url where Klov is running
            klovReporter.initMongoDbConnection(MONGO HOST);  // mongo-db address
   }`

![2018-02-27_20h54_55](https://user-images.githubusercontent.com/29649102/36737196-83f71064-1c00-11e8-845e-e04a32b80bd0.png)

**Comment by akhiljosephk** [comment]
I am using cucumber-extentsreport 3.0.2 version
` <dependency>
            <groupId>com.vimalselvam</groupId>
            <artifactId>cucumber-extentsreport</artifactId>
            <version>3.0.2</version>
        </dependency>`

**Comment by anshooarora** [comment]
MongoDB version?  You need 3.2.

**Comment by akhiljosephk** [comment]
But it's working fine for other projects which are pointing to the same Klov server and mongodb. Only difference is that are not using Cucumber extent report.

**Comment by anshooarora** [comment]
You are attaching the KlovReporter instance in after class. Why? All reporters must be the first thing that ExtentReports must enable. Put these in the code instantiation.

**Comment by akhiljosephk** [comment]
It got resolved after adding below steps:

`String report = "output/extent.html";
 File file = new File(report);
 ExtentCucumberFormatter formatter =new ExtentCucumberFormatter(file);
 Reporter.getExtentReport().attachReporter(klovReporter);`
