### ISSUE TITLE
AddScreenCaptureFromPath fails  - .Net v3.1.0 community 

### ISSUE THREAD

**Issue by SergeyC4** [anshooarora/klov#27]
Hi,
Got Object reference not set to an instance of an object on 
 Test.AddScreenCaptureFromPath(DoTakeScreenshot()) //DoTakeScreenshot() saves screenshot to the disk and returns its full path

Stacktrace:
   at AventStack.ExtentReports.Reporter.KlovReporter.InitMedia()
   at AventStack.ExtentReports.Reporter.KlovReporter.OnScreenCaptureAdded(Test test, ScreenCapture screenCapture)
   at AventStack.ExtentReports.Model.Report.<>c__DisplayClass26_0.<AddScreenCapture>b__0(IExtentReporter x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at AventStack.ExtentReports.Model.Report.AddScreenCapture(Test test, ScreenCapture sc)
   at AventStack.ExtentReports.ExtentTest.AddScreenCaptureFromPath(String path, String title)

All the configurations are default. Running on windows 10, redis = MSOpenTech's redis v2.6.12
Klove 0.0.3

**Comment by anshooarora** [comment]
What other reporters are you using?  Please share complete initialization coffee.

**Comment by SergeyC4** [comment]
Thanks for your reply.

I use only klov reporter: Here is the initialization code:

internal class ExtentManager
    {
        private static readonly ExtentReports _instance = new ExtentReports();

        static ExtentManager()
        {
            KlovReporter klov = new KlovReporter();
            klov.InitMongoDbConnection(ConfigurationManager.AppSettings["ExtentXReportDBHost"],
                Int16.Parse(ConfigurationManager.AppSettings["ExtentXReportDBPort"]));
            klov.ReportName = "report name";
            klov.ProjectName = "project name;
            _instance.AttachReporter(klov);
        }

        public static ExtentReports Instance
        {
            get { return _instance; }
        }
    }

and after that initialize reporter like  Report = ExtentManager.Instance;

**Comment by anshooarora** [comment]
If you don't mind, can you open this in the csharp repo?  It belongs there and I will be able to commit directly to the ticket in the same repo to track.  Thanks.

Closing this ticket as its in the wrong repo.
