### ISSUE TITLE
Using Cucable plugin with Failsafe generates a separate build for each test

### ISSUE THREAD

**Issue by jsa34** [anshooarora/klov#28]
Using the following test class structure for each test generated by Cucable with Failsafe executing the tests, using ExtentCucumberFormatter plugin, each test is considered a separate build on the Klov reporter server.

@RunWith(Cucumber.class)
@CucumberOptions(
        features = {"target/parallel/features/Test_IT.feature"},
        format = {"json:target/cucumber-report/Test_IT.json"},
        glue = {"com.test"},
        plugin = {"com.test.ExtentCucumberFormatter:"}
)

public class Test_IT {
@BeforeClass
public static void setup(){
        ExtentProperties extentProperties=ExtentProperties.INSTANCE;
        extentProperties.setKlovServerUrl(PropertyLoader.getProperty(TestProperties.KLOV_SERVER_URL));
        extentProperties.setProjectName(PropertyLoader.getProperty(TestProperties.PROJECT_NAME));
        extentProperties.setMongoDbServerUrl(PropertyLoader.getProperty(TestProperties.MONGODB_SERVER_HOST));
        extentProperties.setBuildId(PropertyLoader.getProperty(TestProperties.PROJECT_NAME) + "_" + PropertyLoader.getProperty(TestProperties.BUILD_ID)); //Sets klov.setReportName();
        }
} 

I can see in the older ExtentX reporter, you could append tests to a build if the build name was the same.  This would solve my problem here, and if there is a way of appending tests to the same build if the klov.setReportName is identical for tests.

Is there any way to do this?

Many thanks

**Comment by anshooarora** [comment]
Setup should be used only once, at the very beginning.  If you use it before every class, you will have this issue. The ability to append to existing report will be available but above usage is not correct.
