### ISSUE TITLE
Duplicate entries in klov report unlike Html report

### ISSUE THREAD

**Issue by ashwin-ak** [anshooarora/klov#31]
Hi,
I am seeing duplicate entries for specflow steps. Also the feature, scenario and steps shows with full package name, Whereas the standard html report shows fine.

Klov report below:
![image](https://user-images.githubusercontent.com/16545427/37368507-7e949970-272c-11e8-9e25-2e003c2e2012.png)
 
Html report below:
![image](https://user-images.githubusercontent.com/16545427/37368599-c245cf72-272c-11e8-9d58-ea4e40737a08.png)

Please let me know if I am missing some setup.

Thanks,
Ashwin

**Comment by anshooarora** [comment]
fixed

https://github.com/anshooarora/extentreports-csharp/commit/e120da4ec9a4101cde1dc52155148f73100e49e6
