### ISSUE TITLE
Can you show the Steps result information?

### ISSUE THREAD

**Issue by yili1992** [anshooarora/klov#33]
In my case , I have many configuration test , such as BeforeSuite AfterSuite and so on , but I' not wish klov to statistics it, in extendreport , there are Tests and Steps. i want klov show the Steps,  in a additional, in klov , I can't forward to test detail , the test file where be saved in klov server

**Comment by anshooarora** [comment]
Sorry, I do not understand the ask here. Please clarify

**Comment by yili1992** [comment]
sorry, my description is not clear,
in the extentreport , there are two ways to show result "Tests","Steps",  in klov's build pages where it can show "Tests","Steps" like extentreport?
![image](https://github.com/yili1992/ExtendReport/raw/master/asset/1.png)

**Comment by anshooarora** [comment]
It already shows it like this.. See this report for example:

http://klov.herokuapp.com/build?id=5a315071c5c4ff0e38058325
