### ISSUE TITLE
Not able to save screenshot using klov reporter.

### ISSUE THREAD

**Issue by appuCES** [anshooarora/klov#35]
Hi @anshooarora 

I am using both HtmlReporter and KlovReporter for my C-Sharp project. The issue here is, when i try to capture a screenshot in report it is not being saved and visible in klov reporter. But, i can see the screenshot being displayed in HtmlReporter. I'm receiving the below exception.

`System.UriFormatException:` 'Invalid URI: The URI scheme is not valid.'

**Error:**

![image](https://user-images.githubusercontent.com/30317599/37776141-a8db20fc-2e0a-11e8-9af7-eb284ac2f16e.png)

**HtmlReporter:** Screenshot is visible

![image](https://user-images.githubusercontent.com/30317599/37776227-d98d92f2-2e0a-11e8-9941-48b82e474b91.png)

**KlovReporter:** Screenshot is not visible

![image](https://user-images.githubusercontent.com/30317599/37776341-0dda8f2e-2e0b-11e8-8b1b-e16397a252fa.png)

Could you please help me in find the issue here ?

Thanks,
Appu

**Comment by anshooarora** [comment]
This is a known bug currently with the C# version.  Fix will be released soon.

**Comment by anshooarora** [comment]
This is fixed with Klov 0.1.0 and the latest csharp release will be available this week.
