### ISSUE TITLE
Where can i see the klov report

### ISSUE THREAD

**Issue by tanveerfizzz** [anshooarora/klov#40]
Hi,

I ran klov for my project with all the steps mentioned. The build was successful. I am getting the normal Extent Report in testresults folder. My question here is , where will i get the klov report. I did not get the klov report in my db or localhost. can you please advise how can i see the klove report and the steps in detail to see the same.

Thanks in Advance !!

**Comment by anshooarora** [comment]
Where is the server running? Open the same link your browser.

**Comment by tanveerfizzz** [comment]
klovReporter.initMongoDbConnection("localhost", 27017);

Its running at localhost 27017. but when tried to access http://localhost:27017/ on my browser , got below error : It looks like you are trying to access MongoDB over HTTP on the native driver port. Waiting for reply.. Thank you for your help !!

**Comment by anshooarora** [comment]
The statement above is for ExtentReports to log data to MongoDb.

If your MongoDb is running and Extent API is already communicating with it,  and now you would like to setup Klov,  all you have to do is:

1. Download the jar from http://extentreports.com/community/
2. Run Klov using:

```
java -jar klov-0.1.0.jar
```

3. You will now be able to view the server on:  `localhost`.  This is what you need to type in the address bar.
