### ISSUE TITLE
No chart on dashboard, and some js error on pages

### ISSUE THREAD

**Issue by teddylong** [anshooarora/klov#41]
No chart on dashboard section, and some js errors on pages. thanks your time!
<img width="1541" alt="2018-03-30 7 40 16" src="https://user-images.githubusercontent.com/5767152/38136618-38cee6c4-3452-11e8-86bd-6f06e00d2398.png">

**Comment by anshooarora** [comment]
I am closing this ticket as you have not provided any information that helps me understand this issue better.  If you are still having this issue, please open a new ticket.
