### ISSUE TITLE
Do we need nodeJs or any Server or UI to see the Klov report.

### ISSUE THREAD

**Issue by tanveerfizzz** [anshooarora/klov#42]
I ran klov for my project with all the steps mentioned. The build was successful. 
I am getting the normal Extent Report in testresults folder. My question here is , where will i get the klov report.
 I did not get the klov report in my db or localhost. can you please advise how can i see the klove report and the steps in detail to see the same.

klovReporter.initMongoDbConnection("localhost", 27017);

Its running at localhost 27017. but when tried to access http://localhost:27017/ on my browser , got below error : It looks like you are trying to access MongoDB over HTTP on the native driver port.
 Waiting for reply.. Thank you for your help !!

Do we need nodeJs or any Server or UI to see the Klov report.

Thank you !!

**Comment by anshooarora** [comment]
It depends on what host:port Klov is running.

If default settings are used then try `localhost` without specifying a port.

**Comment by tanveerfizzz** [comment]
Hi,
but do we need any UI or the klov report will be displayed on localhost only
?

**Comment by tanveerfizzz** [comment]
Can you please tell me the steps to see the klov report as i am new to Extent reports.
It will be of gr8 help to me.
