### ISSUE TITLE
Signup page error 404 and Update password error 405, Klov community 0.1.0

### ISSUE THREAD

**Issue by csekamal** [anshooarora/klov#43]
Hi,
I was trying to add a new user by clicking the Signup button but I get 404 page does not exist error.
<img width="471" alt="signup_error" src="https://user-images.githubusercontent.com/36864730/38367723-fed3a9de-38d2-11e8-9d58-54541729f1c5.PNG">
When I try to update the password for "root" account I get the below 405, method not allowed error,
<img width="469" alt="password_update_error" src="https://user-images.githubusercontent.com/36864730/38367839-44479a52-38d3-11e8-8691-a3574c7d6e95.PNG">

Are these pages working in klov community version 0.1.0?
Thanks
A.K.

**Comment by anshooarora** [comment]
This functionality is not yet ready, the above is expected.

**Comment by csekamal** [comment]
Are these functionalities, user management, password change, etc are working in the "PRO" version?

**Comment by anshooarora** [comment]
Issue is resolved.  Will be part of 0.1.5 release along with many other enhancements.  Will also be releasing the latest sources with this version.

**Comment by sa-jbrooks** [comment]
Hi @anshooarora, this does not appear to be implemented still; are there plans to release the updated source with this implemented? Thanks!

**Comment by foursyth** [comment]
This has been implemented, see here:  http://klov.herokuapp.com/user/new..  however, this version is not yet available to use.  We should release both the framework and the server in the next few days *fingers crossed*

**Comment by sa-jbrooks** [comment]
@foursyth thanks so much! That's great news. I'll keep an eye out. :)
