### ISSUE TITLE
Delete report with Admin doesn't work

### ISSUE THREAD

**Issue by ramysalama** [anshooarora/klov#47]
Trying to delete a report by clicking on delete button doesn't work, and there is no JS errors fired.
Happening on version "klov-0.1.0.jar"
<img width="2040" alt="screen shot 2018-04-20 at 1 03 31 pm 2" src="https://user-images.githubusercontent.com/18394513/39047756-603150a4-449b-11e8-9964-8e6eb073b433.png">

**Comment by anshooarora** [comment]
Issue is resolved.  Will be part of 0.1.5 release along with many other enhancements.  Will also be releasing the latest sources with this version.
