### ISSUE TITLE
KLOV doesn't seem to be caching any data at Redis

### ISSUE THREAD

**Issue by ramysalama** [anshooarora/klov#48]
I have been trying to use KLOV (0.1.0) with Redis
I did KLOV configuration as the following:
  #spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
spring.session.store-type=redis
server.session.timeout=-1
spring.redis.host=localhost
spring.redis.port=6379

And I was monitoring Redit logs and running redis-cli Monitor, but I can't see any tranactions happening at all
KLOV logs(there is a warning here, I suspect something is wrong):
<img width="1282" alt="klov_logs" src="https://user-images.githubusercontent.com/18394513/39131542-f7fdc0ea-470f-11e8-82d1-f9e9867ce576.png">

Redis debug log:
<img width="548" alt="redis_logs" src="https://user-images.githubusercontent.com/18394513/39131584-1bce59bc-4710-11e8-8a03-1c7519327f85.png">

**Comment by anshooarora** [comment]
Issue is resolved.  Will be part of 0.1.5 release along with many other enhancements.  Will also be releasing the latest sources with this version.
