### ISSUE TITLE
Huge number of build pages causes layout to break

### ISSUE THREAD

**Issue by crasu** [anshooarora/klov#49]
When you have more than 50 pages in the build view. The build view starts to scroll horizontally. 

![too_many_tabs png](https://user-images.githubusercontent.com/232126/39526646-b4c171a2-4e1f-11e8-8246-eaa35086aabf.png)

This was introduced in a version > 0.0.3. Unfourtunatly the source code of versions > 0.0.3 is NOT checked into this github repo. Otherwise I would have prepared a pull request. Is there another place where I can find the code?

Thank you
Christian

**Comment by anshooarora** [comment]
I will check this issue tonight. For a temporary fix, you can increase the page size from application.properties:

```
spring.data.rest.default-page-size=10
```

This will have an impact on a few other areas of the application though, and may slightly increase the page load times.

**Comment by crasu** [comment]
Hi,

Thank you for the workaround. However this does not really fix the issue? Any update on this? I would need the source to fix this myself.

Thank you,
Christian

**Comment by sudpra** [comment]
After deleting all the builds from the current page, navigation between pages showing error page

**Comment by anshooarora** [comment]
Issue is resolved.  Will be released with 0.1.5 soon along with all sources.

**Comment by anshooarora** [comment]
Revamped pagination:

![pagi](https://user-images.githubusercontent.com/4107384/42230539-3f3a200a-7eb7-11e8-9662-01b041edbf12.png)
