### ISSUE TITLE
Last Build Distribution displays the incorrect statistics in the dashboard

### ISSUE THREAD

**Issue by sudpra** [anshooarora/klov#51]
Scenario 1:
In Dashboard, last build distribution chart displays the statistics of the first build completed in that project and not the latest one.

Scenario 2:
Last build distribution displays the same statistics in all the projects available in KLOV server. It not displays the corresponding KLOV project statistic in their corresponding dashboards

KLOV Version: 0.1.1
Extent Version: 3.1.5
Mongo DB : 3.2

Note: I am unable to attach the screenshot here. Getting error 'Something went really wrong, and we can't process that file'

**Comment by gedogarne** [comment]
Having the dame issue.
So last build distribution is never updated accordingly to the runs .
![2018-06-04 11_10_50-klov](https://user-images.githubusercontent.com/35363170/40908783-07a59b50-67e8-11e8-85ec-19ad8ab7eb0a.jpg)

**Comment by foursyth** [comment]
We are looking into this.

**Comment by baraths84** [comment]
I observed the same issue as-well.

**Comment by anshooarora** [comment]
Issue is resolved.  Will be released with 0.1.5 soon along with all sources.

**Comment by gedogarne** [comment]
Perfect! Thanks the earlier the better ;)

Von meinem iPhone gesendet

Am 03.07.2018 um 17:49 schrieb Anshoo Arora <notifications@github.com<mailto:notifications@github.com>>:


Issue is resolved. Will be released with 0.1.5 soon along with all sources.

-
