### ISSUE TITLE
Community version - Environment details not in Klov report

### ISSUE THREAD

**Issue by ashwin-ak** [anshooarora/klov#54]
Hi,

Environment details are shown up in Klov report, where as the html report has.

**Html report**
![environment_html](https://user-images.githubusercontent.com/16545427/42213661-0972abac-7ed7-11e8-87a3-d4b2b80c701d.png)

**Klov report**
![environment_klov](https://user-images.githubusercontent.com/16545427/42213662-09a8bb20-7ed7-11e8-9626-d41a16168b83.png)

Thanks,
Ashwin

**Comment by anshooarora** [comment]
your ExtentReports version?

**Comment by ashwin-ak** [comment]
.Net 3.1.3

**Comment by ashwin-ak** [comment]
Assuming your repositories has the latest version of Extent Reports. I happen to notice environment collection has not been intitialized in c# version but the java version does.

**C# version:**
![image](https://user-images.githubusercontent.com/16545427/42265716-f296626e-7f91-11e8-902e-3e4f18faaa15.png)

**Java version:**
![image](https://user-images.githubusercontent.com/16545427/42265751-17d16308-7f92-11e8-88c4-3b7393e83b32.png)

**following method implementation is missing in C# version-**
![image](https://user-images.githubusercontent.com/16545427/42265849-57df2de0-7f92-11e8-9589-522cbc6785fb.png)

**Comment by anshooarora** [comment]
Thank you. Can you send a pull request?

**Comment by ashwin-ak** [comment]
Have created a pull request
https://github.com/anshooarora/extentreports-csharp/pull/131
