### ISSUE TITLE
Extent Reports Pro version Point of Contact

### ISSUE THREAD

**Issue by baraths84** [anshooarora/klov#55]
Hi, Whom do i reach out to checkout for Pro version details. I am sending email to extentreports@tekstrom.com got reply once with pricing information.. but for subsequent clarification no one is responding to it  ?  Pls advise. 

Thanks

**Comment by anshooarora** [comment]
Thank you, I will check with them.  Generally if the query is for support of the communuty version, you won't get a response quickly and it may take a bit.
