### ISSUE TITLE
klov doesn't change  test chart with new values of the execution

### ISSUE THREAD

**Issue by rubens1287** [anshooarora/klov#64]
My klov doesn't change  test chart with new values of the execution, so I have one execution with 3 features which each has 1 scenario, so I believe that, this chart should be to change value with 3 test case and status.  

Could you check why doesn't work? 

I am saying about below chart

![image](https://user-images.githubusercontent.com/8986981/45118311-83a46080-b12e-11e8-8be4-8fede0053baf.png)

below complete evidence

![image](https://user-images.githubusercontent.com/8986981/45117904-45f30800-b12d-11e8-9c20-0bc8c4acdfa3.png)

![image](https://user-images.githubusercontent.com/8986981/45117989-7cc91e00-b12d-11e8-83ba-0c83ad3c7bdc.png)

![image](https://user-images.githubusercontent.com/8986981/45118449-ee559c00-b12e-11e8-946e-dfda195f1ab5.png)

Since already, thank for help

best regards,
Rubens Lobo

**Comment by foursyth** [comment]
This is a known issue in the current version. The upcoming one (will be available the same time as Extent Framework 4) will resolve this.

**Comment by rubens1287** [comment]
thank for help, I am so glad with that information, so I will wait for new release.

Thaks a lot! :)
