### ISSUE TITLE
Ui distorted in report Page Please find attachment.

### ISSUE THREAD

**Issue by RaghuveerA** [anshooarora/klov#8]
the font color is same as background color so its not able to display.

![screen shot 2017-11-09 at 10 23 30 am](https://user-images.githubusercontent.com/11276009/32589029-4397c10e-c538-11e7-8a58-e73429cccdee.png)
![screen shot 2017-11-09 at 10 23 51 am](https://user-images.githubusercontent.com/11276009/32589030-43d4caae-c538-11e7-8aba-bb95d397399c.png)

**Comment by anshooarora** [comment]
The below should be the correct view, marked as bug.

![img](https://user-images.githubusercontent.com/4107384/32609458-d523261e-c52d-11e7-85d9-74c443f31ba0.png)

**Comment by anshooarora** [comment]
A new reports view is now available:

http://klov.herokuapp.com/reports

**Comment by veeramanikandanvv** [comment]
@anshoo- what difference we can see in klov than extentx
