### ISSUE TITLE
klov-0.2.0 is not displaying canvas charts for Total tests, Builds Executed Today and Tests Executed Today

### ISSUE THREAD

**Issue by Niharmyth** [anshooarora/klov#84]
I have configured the Klov Server using the latest jar "klov-0.2.5". I'm unable to view charts for "Total tests, Builds Executed Today and Tests Executed Today" in the Klov Dashboard. 

Attaching image below

![image](https://user-images.githubusercontent.com/13160953/52190575-083d0b80-2894-11e9-8e71-4471cb244165.png)

**Comment by Niharmyth** [comment]
I have tried opening the Klov Dashboard in various browsers, still the same issue

**Comment by anshooarora** [comment]
Any errors in console? Can you restart and check? If not, does 0.2.4 work?

**Comment by Niharmyth** [comment]
I can see an error in the console 
![image](https://user-images.githubusercontent.com/13160953/52193509-9371cd80-28a3-11e9-9579-9f4582fd8b86.png)

Will downgrade to 0.2.4 and check...

**Comment by Niharmyth** [comment]
![image](https://user-images.githubusercontent.com/13160953/52193621-2e6aa780-28a4-11e9-9b07-39696bf0777d.png)

**Comment by yahyakara** [comment]
I got same issue, When I install ıt showed perfectly but after I restarted server the charts not shows

**Comment by Niharmyth** [comment]
Dropping the database and restarting the service helped. Charts are now being loaded.
